### ISSUE TITLE
iOS UIButton image support

### ISSUE THREAD

**Issue by hokster7** [ide/react-native-button#2]
Consider a simple 'favourite' button. Initially, an empty heart is shown. When pressed, a filled heart is shown.

With a `UIButton`, you would normally go to your Storyboard and set images for the various states that your button could take: e.g. `UIControlStateNormal`, `UIControlStateHighlighted`, `UIControlStateSelected`, `UIControlStateDisabled`.

Since the implementation of this button wraps `TouchOpacity` + `Text`, I suppose it's possible to wrap `TouchOpacity` + `Image`?

**Comment by ide** [comment]
It's possible to wrap almost anything in `TouchOpacity`. My current thinking is that the <Button> should accept any children so that you can choose how to position the image (or maybe you want two images, or some text overlaid on top of an image).

One downside to that approach is that you'd have to manually set the tintColor of the image when the button is disabled; there isn't a good way for the button component to set the tintColor of its children at this time (when React 0.14 comes out this will become possible).

Could you provide an example of the API you'd like (doesn't necessarily have to match Apple's APIs since React is a lot more flexible)?

**Comment by ide** [comment]
I added support for images, so you can write:

```
<Button onPress={...}>
  <Image .../>
</Button>
```

It doesn't do anything special with the `tintColor` for now so you'll have to handle that yourself. Regarding multiple states, the best way to handle that with React is to directly pass in the image you want to display.
